# Generated by Django 4.1.1 on 2022-09-26 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimentos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('crm', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultas.especialidades')),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('laudo', models.TextField(blank=True, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultas.medico')),
                ('procedimentos', models.ManyToManyField(to='consultas.procedimentos')),
            ],
        ),
    ]
