# Generated by Django 4.1.1 on 2022-09-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='procedimentos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
