# Generated by Django 4.1.1 on 2022-09-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_especialidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidades',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
